Support AGP 4.2.2 and 7.0.0-beta04
gradle/android-cache-fix-gradle-plugin pull request #174
Opened 2021-07-02 11:31 UTC by runningcode

2021-07-07 13:44 UTC, ghale requested changes
This looks good, but it looks like there are some new tasks in the latest beta that need to be handled.  As far as I'm concerned, this is good to merge once that test is fixed.

2021-07-08 19:08 UTC, zsperske commented
Minor nitpick but should the title be updated to reflect "beta05" instead of "beta04"?

2021-07-09 13:43 UTC, ghale approved these changes

2021-07-09 13:43 UTC, ghale commented on src/test/groovy/org/gradle/android/CrossVersionOutcomeAndRelocationTest.groovy
> +        // New tasks in 4.2.0-beta04
Are these actually new in 4.2.0?  If so, why are they in the "android7xOrHigher" list?

2021-07-09 13:47 UTC, merged