Enable PTS
gradle/android-cache-fix-gradle-plugin pull request #457
Opened 2023-03-01 21:47 UTC by tylerbertrand

Conditionally enable PTS if the project property 'isPTSEnabled' evaluates to true

Enable PTS in CI if not running against main

2023-03-02 08:38 UTC, runningcode approved these changes

2023-03-02 14:00 UTC, runningcode requested changes
if the property is present, but not set to true, we should also enable PTS. How does it behave if the property is present but not set?

2023-03-02 14:30 UTC, erichaagdev commented on build.gradle
> +        enabled = providers.gradleProperty("isPTSEnabled").map({ it.toBoolean() }).orElse(false)
You can drop the parenthesis for `map`.

```suggestion
        enabled = providers.gradleProperty("isPTSEnabled").map { it.toBoolean() } .orElse(false)
```

2023-03-03 22:24 UTC, erichaagdev commented on build.gradle
> +        enabled = providers.gradleProperty("isPTSEnabled").map { it != 'false' } .orElse(false)
Minor formatting suggestion on my previously suggested minor formatting suggestion:

```suggestion
        enabled = providers.gradleProperty("isPTSEnabled").map { it != "false" }.orElse(false)
```

2023-03-03 22:29 UTC, erichaagdev approved these changes

2023-03-07 15:09 UTC, closed without merging