Develocity Rename
gradle/android-cache-fix-gradle-plugin pull request #637
Opened 2024-01-02 09:17 UTC by runningcode

In this case only the Readme was updated as it was the only place with references.

2024-01-03 09:42 UTC, ribafish approved these changes

2024-01-12 21:17 UTC, erichaagdev requested changes

2024-01-12 21:17 UTC, erichaagdev commented on README.md
> +> - _[Develocity Build Optimization Experiments][develocity-elocity-build-optimization-experiments]_
```suggestion
> - _[Develocity Build Optimization Experiments][develocity-build-optimization-experiments]_
```

2024-01-15 09:58 UTC, runningcode commented on README.md
> +> - _[Develocity Build Optimization Experiments][develocity-elocity-build-optimization-experiments]_
Thanks

2024-01-15 09:58 UTC, merged